name: build0

on:
  schedule:
    - cron: "1 0 */2 * *"
  workflow_dispatch:

jobs:
  build0-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code/initialize repo for use
        uses: actions/checkout@v2

      - name: Installing Dependencies
        run: sudo apt-get install -y git && sudo apt-get install -y libguava-java clamav-freshclam
        
      - name: ls -la
        run: ls -la
        
      - name: cd & get guave googloe deps
        run: cd scripts && wget https://repo1.maven.org/maven2/com/google/guava/guava/33.4.0-jre/guava-33.4.0-jre.jar
      
      - name: cd & list filestructure
        run: cd scripts && ls -la
              
      - name: cd & execute scripts
        run: cd scripts && tail -n +2 */*.csv | sed 's/,/ , /' | awk '{ print $1 }' | sort -u  >> avast-covid19.sha256 && ls -la && java -cp "./guava-33.4.0-jre.jar" Main.java ./avast-covid19.sha256
#        run: cd scripts && java -cp "./guava-33.4.0-jre.jar" Main.java

      - name: cd & ls -la
        run: cd scripts && ls -la

#      - name: clone2
#        run: git clone -b main --single-branch "https://github.com/.git" dir1
      
#      - name: list filestructure
#        run: ls -la
      
#      - name: merge
#        run: rsync -i -a ./revanced-patches2/ ./revanced-patches/
        
#      - name: list filestructure
#        run: ls -la
        
#      - name: delete tempClone2
#        run: rm -rf tempClone2
        
#      - name: delete foreign dotfiles
#        run: rm -rf ./revanced-patches/.git && rm -rf ./revanced-patches/.github && rm -rf ./revanced-patches/.idea
        
#      - name: compress
#        run: 7z a ./rp.7z ./revanced-patches/
        
#      - name: move to root
#        run: rsync -i -a ./revanced-patches/ ./ && rm -rf revanced-patches
        
#      - name: list filestructure
#        run: ls -la
        
#      - name: pull
#        run: git pull
      
      - name: Commit merges
        run: |
          git add -f ./
          git config --global user.name 'Mafiadoener36'
          git config --global user.email 'Mafiadoener36@users.noreply.github.com'
          git commit -am "Automated debugMerge"
          git push